# -*- coding: utf-8 -*-
"""openai_text_speech_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BU5jCvLeyoBF8nC3LEdaxV9G8wCtNq8G
"""

!pip install openai

from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="sk-xxx3X",
)

from pathlib import Path

speech_file_path = Path("samplespeech2.mp3")
response = client.audio.speech.create(
  model="tts-1",
  voice="echo",
  input="Hello world.Welcome to futurexskills"
)

response.stream_to_file(speech_file_path)

