# -*- coding: utf-8 -*-
"""text_classifier_tensorflow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hvEbKfeT1wjNknh7rEL1esIFXusZUHp_
"""

import nltk

nltk.download('all')

import numpy as np
import pandas as pd

dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/Restaurant_Reviews.tsv.txt', delimiter= '\t', quoting = 3)

dataset.head()

from nltk.corpus import stopwords

from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

dataset.info()

corpus = []

import re

for i in range(0, 1000):

  customer_review = re.sub('[^a-zA-Z]', ' ',dataset['Review'][i])
  customer_review = customer_review.lower()
  customer_review = customer_review.split()
  clean_review = [ps.stem(word) for word in customer_review if not word in set(stopwords.words('english'))]
  clean_review = ' '.join(clean_review)
  corpus.append(clean_review)

corpus[0]

corpus[6]

corpus[12]

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features = 1500, min_df = 3, max_df = 0.6)

X = vectorizer.fit_transform(corpus).toarray()

X

X[0]

y = dataset.iloc[:, 1].values

y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

import tensorflow as tf

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(500, activation='relu'),
  tf.keras.layers.Dense(500, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100)

loss, accuracy =model.evaluate(X_test, y_test)

model.summary()

sample = ["Good batting by England"]

sample = vectorizer.transform(sample).toarray()

sample

sentiment = model.predict(sample)[:,1]
 sentiment

sentiment2 = model.predict(vectorizer.transform(["bad performance by India in the match"]).toarray())[:,1]
 sentiment2

model.save('text_classifier_model/1')

!zip -r text_classifier_model.zip text_classifier_model

from google.colab import files

files.download('text_classifier_model.zip')

