# -*- coding: utf-8 -*-
"""openai-api-getting-started.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wmb5KP-c5U4SdkKYnKopA0OpbTF8DBSC
"""

!pip install openai

from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="sk-0nnnnnnnnnnn3X",
)

completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are an expert cook of North American dishes"},
    {"role": "user", "content": "Suggest a good recipe for Thanksgiving dinner"}
  ]
)
print(completion.choices[0].message)

response = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Who won the world series in 2020?"},
    {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
    {"role": "user", "content": "Where was it played?"}
  ]
)

print(response.choices[0].message)

response = client.chat.completions.create(
  model="gpt-3.5-turbo-1106",
  response_format={ "type": "json_object" },
  messages=[
    {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
    {"role": "user", "content": "Who won the world series in 2018?"}
  ]
)
print(response.choices[0].message.content)

print(response.usage.total_tokens)

response = client.completions.create(
  model="gpt-3.5-turbo-instruct",
  prompt="Write a tagline for a travel company"
)

print(response.choices[0].text)

response = client.images.generate(
  model="dall-e-3",
  prompt="a simple cat",
  size="1024x1024",
  quality="standard",
  n=1,
)

image_url = response.data[0].url

image_url

